/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incidents */
        get: operations["incidents_api_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incident */
        get: operations["incident_api_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_incidents__incident_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["audit_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Annotations */
        get: operations["annotations_api_annotations_get"];
        /** Annotate */
        put: operations["annotate_api_annotations_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/adjudication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Adjudication */
        get: operations["adjudication_api_adjudication_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Media */
        get: operations["media_api_media__media_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @enum {string}
         */
        Action: "log_only" | "alert_guard" | "preserve_clip" | "notify_supervisor" | "notify_police" | "call_medical" | "call_fire" | "lock_down_zone" | "dispatch_patrol" | "request_second_camera" | "flag_for_review" | "escalate_human";
        /** Annotation */
        Annotation: {
            /** Clip Id */
            clip_id: string;
            /** Annotator */
            annotator: string;
            /** Score */
            score: number;
            /** Factors */
            factors: {
                [key: string]: number;
            };
            /** Actions */
            actions: components["schemas"]["Action"][];
            /** Spans */
            spans: components["schemas"]["EvidenceSpan"][];
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Complete
             * @default false
             */
            complete: boolean;
            /** Accepted Suggestions */
            accepted_suggestions?: string[];
            /**
             * Adjudication
             * @default false
             */
            adjudication: boolean;
        };
        /**
         * Band
         * @enum {string}
         */
        Band: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /** Claim */
        Claim: {
            /** Claim Id */
            claim_id: string;
            /** Text */
            text: string;
            type: components["schemas"]["ClaimType"];
            /** Entities */
            entities: string[];
            /** Time Span S */
            time_span_s: [
                number,
                number
            ];
            /** Self Confidence */
            self_confidence: number;
            /**
             * Predicate
             * @default unknown
             * @enum {string}
             */
            predicate: "presence" | "count" | "motion" | "contact" | "damage" | "intent" | "unknown";
            /** Counts */
            counts?: {
                [key: string]: number;
            };
        };
        /**
         * ClaimType
         * @enum {string}
         */
        ClaimType: "OBSERVATION" | "INFERENCE" | "UNCERTAINTY";
        /** DecisionRequest */
        DecisionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirm" | "dismiss";
            /** Operator */
            operator: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Detection */
        Detection: {
            /** Detection Id */
            detection_id: string;
            /** Cls */
            cls: string;
            /** Conf */
            conf: number;
            /** Frame */
            frame: number;
            /** Time S */
            time_s: number;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Track Id */
            track_id: number;
        };
        /** Evidence */
        Evidence: {
            /** Objects */
            objects: components["schemas"]["Detection"][];
            /** Tracks */
            tracks: components["schemas"]["Track"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Keyframes */
            keyframes: components["schemas"]["Keyframe"][];
            /** Extractor */
            extractor: string;
            /** Limitations */
            limitations?: string[];
        };
        /** EvidenceSpan */
        EvidenceSpan: {
            /** Start S */
            start_s: number;
            /** End S */
            end_s: number;
            /** Label */
            label: string;
        };
        /** Factor */
        Factor: {
            /** Name */
            name: string;
            /** Raw */
            raw: number;
            /** Weight */
            weight: number;
            /** Contribution */
            contribution: number;
            /** Source Claims */
            source_claims: string[];
            /**
             * Available
             * @default true
             */
            available: boolean;
        };
        /** Features */
        Features: {
            /** Cache Path */
            cache_path: string;
            /** N Snippets */
            n_snippets: number;
            /** Feature Dim */
            feature_dim: number;
            /** Extractor */
            extractor: string;
            /** Cache Key */
            cache_key: string;
            /** Snippet S */
            snippet_s: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Human */
        Human: {
            /**
             * State
             * @default AWAITING_HUMAN_CONFIRMATION
             * @enum {string}
             */
            state: "AWAITING_HUMAN_CONFIRMATION" | "CONFIRMED" | "DISMISSED";
            /** Decision */
            decision?: ("confirm" | "dismiss") | null;
            /** Operator Note */
            operator_note?: string | null;
            /** Decided At */
            decided_at?: string | null;
        };
        /** IncidentRecord */
        IncidentRecord: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Incident Id */
            incident_id: string;
            source: components["schemas"]["Source"];
            pipeline: components["schemas"]["Provenance"];
            m1_features?: components["schemas"]["Features"] | null;
            m2_detection?: components["schemas"]["Localisation"] | null;
            m3_evidence?: components["schemas"]["Evidence"] | null;
            /** M4 Claims */
            m4_claims?: components["schemas"]["Claim"][];
            /** M4 Attempts */
            m4_attempts?: components["schemas"]["VLMOutput"][];
            m5_verification?: components["schemas"]["Verification"] | null;
            m6_severity?: components["schemas"]["Severity"] | null;
            m7_response?: components["schemas"]["Response"] | null;
            human?: components["schemas"]["Human"];
            /** Timing Ms */
            timing_ms?: {
                [key: string]: number;
            };
        };
        /** Keyframe */
        Keyframe: {
            /** Frame */
            frame: number;
            /** Time S */
            time_s: number;
            /** Path */
            path: string;
            /** Reason */
            reason: string;
        };
        /** Localisation */
        Localisation: {
            /** Score Curve */
            score_curve: number[];
            /** T Start S */
            t_start_s: number;
            /** T End S */
            t_end_s: number;
            /** Incident Class */
            incident_class: string;
            /** Class Confidence */
            class_confidence: number;
            /** Model Version */
            model_version: string;
            /** Gt Window S */
            gt_window_s?: [
                number,
                number
            ] | null;
            /** Temporal Iou */
            temporal_iou?: number | null;
        };
        /** Provenance */
        Provenance: {
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Config Hash */
            config_hash: string;
            /** Git Sha */
            git_sha: string;
            /** Seed */
            seed: number;
            /** Module Versions */
            module_versions: {
                [key: string]: string;
            };
        };
        /** Response */
        Response: {
            /** Recommended Actions */
            recommended_actions: components["schemas"]["Action"][];
            /** Policy Rule Id */
            policy_rule_id: string;
            /** Constraint Violations */
            constraint_violations: number;
            /** Stripped Actions */
            stripped_actions: string[];
        };
        /** Severity */
        Severity: {
            /** Score */
            score: number;
            band: components["schemas"]["Band"];
            /** Factors */
            factors: components["schemas"]["Factor"][];
            /** Model Version */
            model_version: string;
            /** Calibration Status */
            calibration_status: string;
        };
        /** Source */
        Source: {
            /** Dataset */
            dataset: string;
            /** Clip Id */
            clip_id: string;
            /** Video Path */
            video_path: string;
            /** Fps */
            fps: number;
            /** Duration S */
            duration_s: number;
            /** Sample */
            sample: boolean;
            /**
             * Split
             * @default demo
             * @enum {string}
             */
            split: "train" | "val" | "test" | "demo";
        };
        /** Track */
        Track: {
            /** Track Id */
            track_id: number;
            /** Cls */
            cls: string;
            /** Frames */
            frames: number[];
            /** Trajectory */
            trajectory: [
                number,
                number
            ][];
        };
        /** VLMOutput */
        VLMOutput: {
            /** Claims */
            claims: components["schemas"]["Claim"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Verification */
        Verification: {
            /** Claims */
            claims: components["schemas"]["VerificationClaim"][];
            /** Hallucination Rate */
            hallucination_rate: number;
            /** N Total */
            n_total: number;
            /** N Verified */
            n_verified: number;
            /** N Rejected */
            n_rejected: number;
            /** N Downgraded */
            n_downgraded: number;
            /**
             * Retry Used
             * @default false
             */
            retry_used: boolean;
            /**
             * Original Rejection Rate
             * @default 0
             */
            original_rejection_rate: number;
        };
        /** VerificationClaim */
        VerificationClaim: {
            /** Claim Id */
            claim_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "VERIFIED" | "REJECTED" | "DOWNGRADED" | "UNCERTAINTY";
            /** Evidence Refs */
            evidence_refs: string[];
            /** Reason */
            reason?: string | null;
            original_type: components["schemas"]["ClaimType"];
            final_type: components["schemas"]["ClaimType"];
            /** Alias Hits */
            alias_hits?: string[];
            /** Observed Counts */
            observed_counts?: {
                [key: string]: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    incidents_api_incidents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentRecord"][];
                };
            };
        };
    };
    incident_api_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_incidents__incident_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_api_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    annotations_api_annotations_get: {
        parameters: {
            query: {
                annotator: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Annotation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annotate_api_annotations_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Annotation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Annotation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjudication_api_adjudication_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Annotation"][];
                };
            };
        };
    };
    media_api_media__media_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
